### ISSUE TITLE
svelte-prism and sveltejs/kit (svelte@next)

### ISSUE THREAD

**Issue by mweissen** [jakobrosenberg/svelte-prism#18]
I have installed the sveltejs/kit and svelte-prism:
```
mkdir prismtest
cd prismtest
npm init svelte@next
npm install
npm i svelte-prism
```
Then:
`import Prism from 'svelte-prism';`
I get:

```
Prism is not defined

ReferenceError: Prism is not defined
    at /node_modules/prism-svelte/index.js?v=8d61b37f:1:1
    at instantiateModule (C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69030:166)

```

Another error message was

```
08:46:50 [vite] Error when evaluating SSR module /node_modules/prism-svelte/index.js?v=8d61b37f:
ReferenceError: Prism is not defined
    at /node_modules/prism-svelte/index.js?v=8d61b37f:3:1
    at instantiateModule (C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69030:166)
08:46:50 [vite] Error when evaluating SSR module /node_modules/svelte-prism/src/beforeImport.js:
ReferenceError: window is not defined
    at /node_modules/svelte-prism/src/beforeImport.js:1:1
    at instantiateModule (C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69030:166)
08:47:34 [vite] page reload src/routes/index.svelte
08:47:47 [vite] hmr update /src/routes/index.svelte
08:47:51 [vite] Error when evaluating SSR module /node_modules/svelte-prism/src/beforeImport.js:
ReferenceError: window is not defined
    at /node_modules/svelte-prism/src/beforeImport.js:1:1
    at instantiateModule (C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69030:166)
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:67907:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:67976:22)
    at C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:68936:34
    at String.replace (<anonymous>)
    at C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:68926:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:68925:10)
    at Object.ssrFixStacktrace (C:\Svelte\prismtest\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69181:27)
    at Object.get_stack (file:///C:/Svelte/prismtest/node_modules/@sveltejs/kit/dist/chunks/index2.js:3367:19)
    at respond (file:///C:/Svelte/prismtest/node_modules/@sveltejs/kit/dist/ssr.js:2358:33)

```

sveltejs/kit uses vite. Maybe this is the cause?

**Comment by jakobrosenberg** [comment]
Hi @mweissen . Very sorry about the late reply. If this is still an issue, could you try install  `prismjs` as a devDependency.

**Comment by matths** [comment]
I think the problem still exists and is related to window being not available when prism is run server side (build time) instead of on the client (run time).
I guess some check for both cases needs to be done somewhere in the code or something being wrapped in an onMount.

**Comment by NickLarsenNZ** [comment]
This is still a problem, even when importing `prismjs` as a dev-dependency
