### ISSUE TITLE
`line` must be greater than 0 (lines start at line 1) (sveltekit)

### ISSUE THREAD

**Issue by tristan-f-r** [jakobrosenberg/svelte-prism#36]
I'm getting a weird error on SvelteKit:

```
window is not defined
`line` must be greater than 0 (lines start at line 1)
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/home/leodog896/Documents/GitHub/svelte-tilt/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:1780:19)
    at /home/leodog896/Documents/GitHub/svelte-tilt/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:59183:25
    at String.replace (<anonymous>)
    at /home/leodog896/Documents/GitHub/svelte-tilt/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:59173:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/home/leodog896/Documents/GitHub/svelte-tilt/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:59172:10)
    at Object.ssrRewriteStacktrace (/home/leodog896/Documents/GitHub/svelte-tilt/node_modules/vite/dist/node/chunks/dep-e1fc1d62.js:59912:20)
    at fix_stack_trace (file:///home/leodog896/Documents/GitHub/svelte-tilt/node_modules/@sveltejs/kit/dist/chunks/index.js:175:31)
    at Object.get (file:///home/leodog896/Documents/GitHub/svelte-tilt/node_modules/@sveltejs/kit/dist/chunks/index.js:309:21)
    at Object.hooks.handleError (file:///home/leodog896/Documents/GitHub/svelte-tilt/node_modules/@sveltejs/kit/dist/chunks/index.js:243:20)
    ```.

I assume that it's because the module isn't SSR compatible.

**Comment by yousufiqbal** [comment]
Same here..

**Comment by JayChamp1** [comment]
Same issue!

**Comment by kuchaguangjie** [comment]
Same here

**Comment by jakobrosenberg** [comment]
`1.1.6` is out. Please let me know if this is still an issue.
