### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by kuchaguangjie** [jakobrosenberg/svelte-prism#41]
When use it according to README, got error.

**Code:**
```
<script>
  import Prism from 'svelte-prism'
</script>

<Prism language="html">
  {`
      <header>
        <h1>Hello World!</h1>
      </header>
    `}
</Prism>
```

**Error:**
```
500
window is not defined
ReferenceError: window is not defined
    at /node_modules/.pnpm/registry.npmmirror.com+svelte-prism@1.1.5/node_modules/svelte-prism/src/beforeImport.js:1:1
    at instantiateModule (file:///mnt/star/workplace/jetbrains/webstorm_workplace/go-fit-web/node_modules/.pnpm/registry.npmmirror.com+vite@3.0.0/node_modules/vite/dist/node/chunks/dep-561c5231.js:50293:15)
```

**Comment by jakobrosenberg** [comment]
This should be fixed in `1.1.6`. If this is not the case, please let me know and I'll reopen.

**Comment by kuchaguangjie** [comment]
With `1.1.6`, still get error:
```
500
The requested module '/node_modules/.pnpm/registry.npmmirror.com+prismjs@1.28.0/node_modules/prismjs/prism.js?v=44353d4b' does not provide an export named 'default'
SyntaxError: The requested module '/node_modules/.pnpm/registry.npmmirror.com+prismjs@1.28.0/node_modules/prismjs/prism.js?v=44353d4b' does not provide an export named 'default'
```

**Comment by jakobrosenberg** [comment]
The second error seems different. Do you know if it's specific to `pnpm` or do you also get it with `npm` or `yarn`?

**Comment by kuchaguangjie** [comment]
I'm using `pnpm`, didn't use npm or yarn, pnpm is much faster ...
